### ISSUE TITLE
Configuration Error with Jalali Calendar Option in dayjs

### ISSUE THREAD

**Issue by erfanfarhadi75** [sssajjad007/jalali-plugin-dayjs#1]
![image](https://github.com/user-attachments/assets/7b265bfb-34e9-4714-a032-8ab4cca7e05b)

I encountered an issue when trying to use the Jalali calendar with the dayjs library. It appears that the **_jalali_** option is not recognized in the configuration object, which results in TypeScript errors.
I was using the **@zoomit/dayjs-jalali-plugin** without encountering any errors like this.

    "dayjs": "^1.11.12",
    "jalali-plugin-dayjs": "^1.1.3",
    "@angular/core": "^17.1.1",
    "typescript": "^5.2.2"

![image](https://github.com/user-attachments/assets/290a5129-74bb-42ff-8292-4f6f16bb4939)

Although I bypassed it as shown below, it works fine.

![image](https://github.com/user-attachments/assets/fc12be3a-d4d5-421e-a6d7-5f4571636d93)

**Comment by sssajjad007** [comment]
Hi @erfanfarhadi75 
This issue has been fixed in this PR.
feel free to reopen it.

**Comment by erfanfarhadi75** [comment]
Hi @sssajjad007 
Thank you for the update! I appreciate you taking the time to address the issue. I'll review the changes, and if there's anything further needed, I'll let you know.
